"""Initial schema for Flowlite database

Revision ID: 001
Revises:
Create Date: 2025-10-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create User table
    op.create_table('User',
        sa.Column('id_user', mysql.CHAR(36), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True, default=True),
        sa.PrimaryKeyConstraint('id_user'),
        sa.UniqueConstraint('email')
    )

    # Create Role table
    op.create_table('Role',
        sa.Column('id_role', mysql.CHAR(36), nullable=False),
        sa.Column('role_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id_role')
    )

    # Create UserInfo table
    op.create_table('UserInfo',
        sa.Column('id_user', mysql.CHAR(36), nullable=False),
        sa.Column('primerNombre', sa.String(length=100), nullable=True),
        sa.Column('segundoNombre', sa.String(length=100), nullable=True),
        sa.Column('primerApellido', sa.String(length=100), nullable=True),
        sa.Column('segundoApellido', sa.String(length=100), nullable=True),
        sa.Column('telefono', sa.String(length=20), nullable=True),
        sa.Column('direccion', sa.String(length=255), nullable=True),
        sa.Column('ciudad', sa.String(length=100), nullable=True),
        sa.Column('departamento', sa.String(length=100), nullable=True),
        sa.Column('pais', sa.String(length=100), nullable=True),
        sa.Column('numeroIdentificacion', sa.String(length=50), nullable=True),
        sa.Column('numeroIdentificacoin', sa.String(length=50), nullable=True),
        sa.Column('tipoIdentificacion', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
        sa.PrimaryKeyConstraint('id_user')
    )

    # Create Bank table
    op.create_table('Bank',
        sa.Column('id_bank', mysql.CHAR(36), nullable=False),
        sa.Column('bank_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id_bank')
    )

    # Create TransactionCategory table
    op.create_table('TransactionCategory',
        sa.Column('id_category', mysql.CHAR(36), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id_category')
    )

    # Create InsightCategory table
    op.create_table('InsightCategory',
        sa.Column('id_category', mysql.CHAR(36), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id_category')
    )

    # Create TransactionBatch table
    op.create_table('TransactionBatch',
        sa.Column('id_batch', mysql.CHAR(36), nullable=False),
        sa.Column('process_status', sa.String(length=50), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('batch_size', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id_batch')
    )

    # Create Transaction table
    op.create_table('Transaction',
        sa.Column('id_transaction', mysql.CHAR(36), nullable=False),
        sa.Column('id_user', mysql.CHAR(36), nullable=False),
        sa.Column('id_category', mysql.CHAR(36), nullable=False),
        sa.Column('id_bank', mysql.CHAR(36), nullable=True),
        sa.Column('id_batch', mysql.CHAR(36), nullable=True),
        sa.Column('transaction_name', sa.String(length=255), nullable=False),
        sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('transaction_date', sa.DateTime(), nullable=False),
        sa.Column('transaction_type', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['id_bank'], ['Bank.id_bank'], ),
        sa.ForeignKeyConstraint(['id_batch'], ['TransactionBatch.id_batch'], ),
        sa.ForeignKeyConstraint(['id_category'], ['TransactionCategory.id_category'], ),
        sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
        sa.PrimaryKeyConstraint('id_transaction')
    )

    # Create Insights table
    op.create_table('Insights',
        sa.Column('id_insight', mysql.CHAR(36), nullable=False),
        sa.Column('id_user', mysql.CHAR(36), nullable=False),
        sa.Column('id_category', mysql.CHAR(36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('relevance', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['id_category'], ['InsightCategory.id_category'], ),
        sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
        sa.PrimaryKeyConstraint('id_insight')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Insights')
    op.drop_table('Transaction')
    op.drop_table('TransactionBatch')
    op.drop_table('InsightCategory')
    op.drop_table('TransactionCategory')
    op.drop_table('Bank')
    op.drop_table('UserInfo')
    op.drop_table('Role')
    op.drop_table('User')
    # ### end Alembic commands ###
