version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flowlite-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-flowlite_db}
      MYSQL_USER: ${MYSQL_USER:-flowlite_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-flowlite_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - flowlite-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: flowlite-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"      # AMQP port
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"  # Management UI
    volumes:
      - ./rabbitmq/config:/etc/rabbitmq
    networks:
      - flowlite-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    command: bash -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"

  flowlite-redis:
    image: redis:7-alpine
    container_name: flowlite-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-flowlite_redis_pass_2024} --maxmemory 256mb --maxmemory-policy allkeys-lru
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-flowlite_redis_pass_2024}
    networks:
      - flowlite-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-flowlite_redis_pass_2024}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    container_name: flowlite-db-init
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-flowlite_db}
      MYSQL_USER: ${MYSQL_USER:-flowlite_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-flowlite_password}
      DATABASE_URL: mysql+pymysql://${MYSQL_USER:-flowlite_user}:${MYSQL_PASSWORD:-flowlite_password}@mysql:3306/${MYSQL_DATABASE:-flowlite_db}
    networks:
      - flowlite-network
    restart: "no"

networks:
  flowlite-network:
    driver: bridge
