"""Initial migration

Revision ID: f61a2a07e91e
Revises: 
Create Date: 2025-10-27 00:27:01.881585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61a2a07e91e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bank',
    sa.Column('id_bank', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_bank')
    )
    op.create_table('InsightCategory',
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('Role',
    sa.Column('id_role', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('TransactionBatch',
    sa.Column('id_batch', sa.UUID(), nullable=False),
    sa.Column('process_status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_batch')
    )
    op.create_table('TransactionCategory',
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('User',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Insights',
    sa.Column('id_insight', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['InsightCategory.id_category'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id_insight')
    )
    op.create_table('Transaction',
    sa.Column('id_transaction', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('id_bank', sa.UUID(), nullable=True),
    sa.Column('id_batch', sa.UUID(), nullable=True),
    sa.Column('transaction_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_bank'], ['Bank.id_bank'], ),
    sa.ForeignKeyConstraint(['id_batch'], ['TransactionBatch.id_batch'], ),
    sa.ForeignKeyConstraint(['id_category'], ['TransactionCategory.id_category'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transaction')
    op.drop_table('Insights')
    op.drop_table('User')
    op.drop_table('TransactionCategory')
    op.drop_table('TransactionBatch')
    op.drop_table('Role')
    op.drop_table('InsightCategory')
    op.drop_table('Bank')
    # ### end Alembic commands ###
